USE [master]
GO

/****** Object:  Database [avito]    Script Date: 16.09.2014 15:20:24 ******/
DROP DATABASE [avito]
GO

/****** Object:  Database [avito]    Script Date: 16.09.2014 15:20:24 ******/
CREATE DATABASE [avito]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'avito', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\avito.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'avito_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\avito_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [avito] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [avito].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [avito] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [avito] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [avito] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [avito] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [avito] SET ARITHABORT OFF 
GO

ALTER DATABASE [avito] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [avito] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [avito] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [avito] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [avito] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [avito] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [avito] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [avito] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [avito] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [avito] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [avito] SET  DISABLE_BROKER 
GO

ALTER DATABASE [avito] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [avito] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [avito] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [avito] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [avito] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [avito] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [avito] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [avito] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [avito] SET  MULTI_USER 
GO

ALTER DATABASE [avito] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [avito] SET DB_CHAINING OFF 
GO

ALTER DATABASE [avito] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [avito] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [avito] SET  READ_WRITE 
GO


